### ISSUE TITLE
Incorrect Usage of `ABSPATH` which breaks sites using custom WordPress install paths

### ISSUE THREAD

**Issue by timnolte** [BoldGrid/library#114]
The code here:

https://github.com/BoldGrid/library/blob/master/src/Library/Start.php#L181-L187

doesn't work properly to determine the actual WordPress path when WordPress Core is installed in an alternative place. This causes major plugin broken UI issues as CSS & JS assets can't be loaded properly. This should be using WordPress Core methods for determining paths & URLs.

The issue was originally reported here: https://github.com/BoldGrid/boldgrid-backup/issues/546

**Comment by timnolte** [comment]
FYI, doing some testing and what is working is the following code:

```php
                if ( ! empty( $configs['libraryDir'] ) ) {
                        $configs['libraryUrl'] = plugin_dir_url( $configs['libraryDir']  . '/src' );   
                }
```

**Comment by bwmarkle** [comment]
@timnolte thanks for the bug ticket! Currently reviewing...
