### ISSUE TITLE
WP Cli reseller support

### ISSUE THREAD

**Issue by rramo012** [BoldGrid/library#15]
Create the ability for resellers to do the following. 

- Create a connect key and attach to wp install, via WP Cli
- Claim an install so that when a user follows the standard key creation process, the key is associated to the reseller. This would allow us to introduce the straight to premium flow, via WP Cli
- Place a file somewhere on the users environment, that we read when a new connect key is created, which will associate the reseller with the connect key 

These methods should be documented in our API/Reseller docs.

**Comment by timelsass** [comment]
How does this pertain to the library?  
Would this code need to live in all plugins?  

It seems like for resellers this might be something that should go into a must use plugin specifically for their own environment.  It wouldn't make much sense to distribute code that is intended for less than 1% of users to everyone.  

Also keep in mind not everyone has wp-cli - or wants to use it, so this should be an afterthought for convenience once the main process is created in a standard way that is accessible to everyone.

**Comment by nicolepaschen** [comment]
Where should this request go?  We would like it to stay open in the appropriate place.
-Products Department

**Comment by timelsass** [comment]
This is not a dumping ground for things that have no place, it should go in JIRA is my guess if it is felt like a repo should be created for resellers or anything new of that nature.

**Comment by timelsass** [comment]
Please answer the questions above if you feel this ticket belongs here when reopening.
