### ISSUE TITLE
Remove Staging from Plugins > Add New > BoldGrid Plugins

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/library#28]
The last time I tested Staging (I tested with Crio last summer), Staging only worked with the 20 Inspiration themes. Users would install the plugin automatically by going thru the Inspiration process a 2nd time and installing that 2nd site to Staging. With Inspirations 2.0 when a user goes thru the 2nd time the site is just replaced. 

If you activate Staging you can assign pages to different development groups but you can't have a 2nd theme active. There's no 'launch staging site' option anymore so I'm not sure how helpful this plugin is at the moment.

**Comment by timelsass** [comment]
It sounds like you might not be familiar with how the staging plugin works.  There is a [guide available in the support center](https://www.boldgrid.com/support/getting-to-know-boldgrid/understanding-active-vs-staging-in-boldgrid/), and the section "Themes" may be helpful.  You can stage a theme by going to "Appearances > Themes" and selecting the theme you wish to stage.

In looking at staging it looks like the "staging switcher" in wpadminbar doesn't update the URL for me for previews, but using the other methods of viewing the active/staging site on the frontend all seem to work fine.

**Comment by timelsass** [comment]
opened https://github.com/BoldGrid/boldgrid-staging/issues/2 for reference to above bug mentioned.

**Comment by timelsass** [comment]
In testing, I went to  "Appearances > Deploy Staging" from the dashboard:
![image](https://user-images.githubusercontent.com/11907254/56971249-e1127500-6b36-11e9-8165-483e4a3fbf74.png)

Is this the "Launch Staging Site" option you're referring to?  I'm not aware of other routes to get to this.

Inspirations v1 provided additional options to install a site as a staging site if the user didn't have an active site.  This isn't related to the staging plugin though.

I tested the customizer active/staged swapping, and it seems to work as it used to, so other than the above bug opened - I'm not seeing anything else.  Do you have more details/steps/information about what is broken and how it can be replicated with the Staging plugin?
