### ISSUE TITLE
As a Reseller Customer, I am given custom feedback if user email exists in Central database

### ISSUE THREAD

**Issue by cssjoe** [BoldGrid/library#4]
The current connect key notice prompt asks for the users current connect key or to create a new key. If the user already has a connect key but isn't aware, they request a new key. We end up with users who have multiple connect keys. This causes several issues. 

We can limit this by checking the wordpress' email address to see if it's associated to a central account before allowing the user request a new connect key.

Joe and I talked about checking wp default email, users email, and a custom option specifically for this purpose.  

Note: This is only an issue if the email a user enters is different that the email used for the connect key.

**Comment by timelsass** [comment]
Resolved by https://github.com/BoldGrid/library/issues/17 as the user handles connect keys on central with this change.  If this is still an issue in context of central, feel free to open an issue in that repo.
