### ISSUE TITLE
As a user, I can enable two factor authentication

### ISSUE THREAD

**Issue by cssjoe** [BoldGrid/library#5]
A user can enable 2FA to add protection to their existing login.
An admin can force all users to use 2FA.
An admin can force all users to login to Central (also having optional 2FA).

The user would be presented with a QR code, private key, and backup codes.  The method would be time based, and compatible with Google Authenticator.

**Comment by timelsass** [comment]
this has no place in the library, and it's code shouldn't be universal or shared across multiple plugins.  There are in fact several 2FA plugins that exist for WordPress already, so maybe just use one of those if you need that level of security.
